language: python

python:
  - "3.6.6"

sudo: enabled

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq blender

install:
- cd ~
- wget http://download.blender.org/release/Blender2.79/blender-2.79-linux-glibc219-x86_64.tar.bz2
- tar -xf blender-2.79-linux-glibc219-x86_64.tar.bz2
- BLENDER_EXEC=$(pwd)/blender-2.79-linux-glibc219-x86_64/blender
- cd $TRAVIS_BUILD_DIR
- pip install -r requirements.txt

script:
- python -m unittest discover -v
- $BLENDER_EXEC -b -P install_addon.py -noaudio 1> /dev/null
- $BLENDER_EXEC -b -P tests/blender_tests.py -noaudio 1> /dev/null