language: python
sudo: enabled
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq blender
script:
- cd $TRAVIS_BUILD_DIR
- pwd
- blender -b -P install_addon.py
- blender -b -P tests/tests.py