language: python

python:
# Enforce the same Python version as bundled with Blender 2.79.
- "3.6.6"

sudo: enabled

before_install:
# The Blender version in the repos is old, but use apt-get to grab the Blender system dependencies.
- sudo apt-get update -qq
- sudo apt-get install -qq blender

install:
# Aquire Blender version 2.79 and bind executable to env variable.
- cd ~
- wget http://download.blender.org/release/Blender2.79/blender-2.79-linux-glibc219-x86_64.tar.bz2
- tar -xf blender-2.79-linux-glibc219-x86_64.tar.bz2
- BLENDER_EXEC=$(pwd)/blender-2.79-linux-glibc219-x86_64/blender
# Install add-on dependencies.
- cd $TRAVIS_BUILD_DIR
- pip install -r requirements.txt
# Prepare the add-on for installation.
- zip -r blender_hand_drawn_npr.zip blender_hand_drawn_npr
# Install the add-on.
- $BLENDER_EXEC -b -P install_addon.py -noaudio 1> /dev/null

script:
# Run tests.
- $BLENDER_EXEC -b -P tests/tests.py -noaudio 1> /dev/null